default_publication: "midaily"
contact_address: "bhl-digital-support@umich.edu"
permissions_address: "bhl-student-pub-contact@umich.edu"

new_google_recaptcha:
  secret_key: secret_key.invalid
  site_key: site_key.invalid
  minimum_score: 0.5  

DLXS_COLLECTION: "bhl_midaily"
DLXS_SERVICE_URL: "https://path/to/service/host"

GOOGLE_ANALYTICS_PROFILES: []

icons:
  rotate_left: "rotate_left"
  rotate_right: "rotate_right"
  zoom_in: "add"
  zoom_out: "remove"
  pan: "arrow_all"
  select: "selection"

  alert: "warning"

  file_image: "image_file"
  file_pdf: "pdf"
  file_text: "text_file"
  file_zip: "text_file"

  next: "arrow_forward"
  previous: "arrow_back"
  divider: "keyboard_arrow_right"
  back_to_top: "keyboard_arrow_up"

  close: "close"
  search: "search"

  info: "info_outline"

